### ISSUE TITLE
Quoted text in comments not showing up properly

### ISSUE THREAD

**Issue by norrir** [ejbills/OpenArtemis#35]
Edit: this may to be affecting other text formattings as well, at least I’ve come across a strikethrough appearing as normal text. Included ss of it below. I also noticed that the bullets in the same comment weren’t respected either

The first block of quoted text will show up as unquoted text. Any subsequent blocks, if any, show up correctly. See attached images for examples

![IMG_3827](https://github.com/ejbills/OpenArtemis/assets/55611093/fa313c77-e743-488a-a22a-573494366ef8)
![IMG_3826](https://github.com/ejbills/OpenArtemis/assets/55611093/0556503a-1b39-42e7-a319-f5ac3200ba59)
![IMG_3825](https://github.com/ejbills/OpenArtemis/assets/55611093/347981ac-54bf-4385-b548-8c586c227baa)
![IMG_3824](https://github.com/ejbills/OpenArtemis/assets/55611093/4c3ddd96-d5ef-4e24-ac0d-cd81806ed4d9)
![IMG_3829](https://github.com/ejbills/OpenArtemis/assets/55611093/dbb67b0b-925d-4e88-b758-fd0203782f0d)
![IMG_3828](https://github.com/ejbills/OpenArtemis/assets/55611093/b9dbe8e8-2c44-4452-a0cd-ee017c72b51e)
![IMG_3831](https://github.com/ejbills/OpenArtemis/assets/55611093/4dd92dba-fe18-4fb9-ad9a-65d5824f4634)
![IMG_3830](https://github.com/ejbills/OpenArtemis/assets/55611093/ccbfde13-a299-471e-8d8f-f3facadc306d)

**Comment by iitzRichie** [comment]
Weird because for me Block Quotes work properly. In testing it myself with comments from my own account and adding multiple quotes, they all appear to work properly. None are left out.

Other formattings don't work properly though (Spoiler, Strikethrough, etc).

**Comment by norrir** [comment]
> Weird because for me Block Quotes work properly. In testing it myself with comments from my own account and adding multiple quotes, they all appear to work properly. None are left out.
> 
> Other formattings don't work properly though (Spoiler, Strikethrough, etc).

Hmm that’s interesting. I came across this and the block quotes show up fine: https://www.reddit.com/r/pics/comments/1bdord8/paul_alexander_78_dies_after_being_in_an_iron/

However, visiting my prior example, they still don’t appear as expected. Please take a look at this one on your end and see how it appears: https://www.reddit.com/r/pcmasterrace/comments/1bd41mm/you_can_now_officially_uninstall_microsoft_edge/

Maybe it’s dependent on how the quote was submitted? Either bc of different apps or the glitchy Reddit site itself (I recall having my clipboard item being auto embedded into replies as quotes on the Reddit site. Could this be a cause)? I should have saved the other links

**Comment by norrir** [comment]
Oops. Didn’t meant to close the issue

**Comment by iitzRichie** [comment]
> Hmm that’s interesting. I came across this and the block quotes show up fine: https://www.reddit.com/r/pics/comments/1bdord8/paul_alexander_78_dies_after_being_in_an_iron/
> 
> However, visiting my prior example, they still don’t appear as expected. Please take a look at this one on your end and see how it appears: https://www.reddit.com/r/pcmasterrace/comments/1bd41mm/you_can_now_officially_uninstall_microsoft_edge/
> 
> Maybe it’s dependent on how the quote was submitted? Either bc of different apps or the glitchy Reddit site itself (I recall having my clipboard item being auto embedded into replies as quotes on the Reddit site. Could this be a cause)? I should have saved the other links

Yeah, that second link even on my end doesn't appear as expected. I'm very confused what the issue is. Even testing different quote styles myself submitted via Old and New Reddit, plus various Reddit apps, it all shows up fine. We'll need the devs input on that. I'm just a fan of the app that likes to help out where I can.

Artemis piggybacks off old.Reddit though, so keep that in mind. Whatever has been implemented for New Reddit wouldn't work.
