### ISSUE TITLE
BUG: Unable to close displayed image

### ISSUE THREAD

**Issue by gottsman** [ejbills/OpenArtemis#40]
Description: When clicking on an image to view, I am unable to close out or go back to the post. There is the share icon and I can zoom, but I can't figure out how to go back to the post without exiting the application.

Steps to Reproduce:

Open the app.
Open a post and click on the associated image. Image displays full screen without a way to go back.

Expected Behavior: Expecting a "X" in the corner or a close button

Actual Behavior: Must close application and relaunch

Additional Information:
Device: iPhone 14 Pro
iOS Version: 17.4

**Comment by iitzRichie** [comment]
It's an app that's native to iOS, meaning that you swipe a lot. To exit from an image you simply just swipe down. (note: when the image is fully zoomed in you can't swipe out of it and instead you have to zoom out then swipe away).

That being said, a little _X_ in a corner would be a nice little visual indicator for exiting an image.

**Comment by gottsman** [comment]
Been an iPhone user since the 3G and never knew that... Must be old like the kids say.

I'm used to Apollo which had the "X". I am all set now.
